version: '3.9'

########################### NETWORKS
networks:
  proxy_traefik:
    name: proxy_traefik
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PROXY_TRAEFIK_SUBNET_IP}

########################### SERVICES
services:
  portainer_edge_agent: # Doesn't need traefik
    image: portainer/agent:latest
    container_name: portainer_edge_agent
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy_traefik
    volumes:
      - /:/host
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/app/portainer/data:/data
    environment:
      - CAP_HOST_MANAGEMENT=1
      - EDGE=1
      - EDGE_ID=${EDGE_ID}
      - EDGE_KEY=${EDGE_KEY}

  # qbittorrent: # qBittorrent - Torrent downloader
  #   image: linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   restart: always
  #   network_mode: container:transmission-vpn
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - $DOCKERDIR/qbittorrent:/config
  #     - $USERDIR/Downloads:/downloads
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #     TZ: $TZ
  #     UMASK_SET: 002
  #     WEBUI_PORT: 8168
  #   labels:
  #     - 'traefik.enable=true'
  #     ## HTTP Routers
  #     - 'traefik.http.routers.qbittorrent-rtr.entrypoints=https'
  #     - 'traefik.http.routers.qbittorrent-rtr.rule=Host(`qbit.$DOMAINNAME_CLOUD_SERVER`)'
  #     - 'traefik.http.routers.qbittorrent-rtr.tls=true'
  #     ## Middlewares
  #     - 'traefik.http.routers.qbittorrent-rtr.middlewares=chain-oauth@file'
  #     ## HTTP Services
  #     - 'traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc'
  #     - 'traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8168'
