version: '3.9'

########################### NETWORKS
networks:
  default:
    driver: bridge
  proxy_traefik:
    name: proxy_traefik
    # external: true
    ipam:
      config:
        - subnet: 172.20.200.0/24
  # TODO - Socket Proxy

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections
# More Info on how to use this: https://github.com/htpcBeginner/docker-traefik/pull/228

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the core services that we always to automatically restart on failure
x-common-keys-core: &common-keys-core
  networks:
    - proxy_traefik
  security_opt:
    - no-new-privileges:true
  restart: always

# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys-apps
  networks:
    - proxy_traefik
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

# Keys common to some of the services in media-services.txt
x-common-keys-media: &common-keys-media
  networks:
    - proxy_traefik
  security_opt:
    - no-new-privileges:true
  restart: 'no'

########################### SERVICES
services: # All services / apps go below this line
  portainer_edge_agent: # Agent       # TODO Route this through Traefik too
    image: portainer/agent:latest
    container_name: portainer_edge_agent
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /:/host
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_agent_data:/data
    environment:
      - CAP_HOST_MANAGEMENT=1
      - EDGE=1
      - EDGE_ID=${EDGE_ID}
      - EDGE_KEY=${EDGE_KEY}

  qbittorrent: # qBittorrent - Torrent downloader
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    network_mode: container:transmission-vpn
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/qbittorrent:/config
      - $USERDIR/Downloads:/downloads
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 002
      WEBUI_PORT: 8168
    labels:
      - 'traefik.enable=true'
      ## HTTP Routers
      - 'traefik.http.routers.qbittorrent-rtr.entrypoints=https'
      - 'traefik.http.routers.qbittorrent-rtr.rule=Host(`qbit.$DOMAINNAME_CLOUD_SERVER`)'
      - 'traefik.http.routers.qbittorrent-rtr.tls=true'
      ## Middlewares
      - 'traefik.http.routers.qbittorrent-rtr.middlewares=chain-oauth@file'
      ## HTTP Services
      - 'traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc'
      - 'traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8168'
