accessLog:
  bufferingSize: 100
  filePath: /logs/traefik-access.log
  filters:
    minDuration: 10ms
    retryAttempts: true
    statusCodes: ['204-299', '400-499', '500-599']
  format: json

api:
  dashboard: true
  insecure: false

certificatesResolvers:
  le-dns-cf: # Using LetsEncrypt + DNS challenge + Clouflare provider
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory # Prod
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # Staging
      dnschallenge:
        delaybeforecheck: 10
        provider: cloudflare
        resolvers: ['1.1.1.1:53', '1.0.0.1:53']
      email: luffy.obrien+letsencrypt@outlook.com
      keyType: RSA4096
      storage: /acme.json

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: le-dns-cf
        domains:
          main: dronico.net
          sans:
            - '*.dronico.net'
        options: tls-opts@file
    forwardedHeaders:
      trustedIPs:
        [
          '127.0.0.1/32',
          '10.0.0.0/8',
          '192.168.0.0/16',
          '172.16.0.0/12',
          '172.20.0.0/24',
          '172.20.20.0/26',
          '172.20.20.64/26',
          '173.245.48.0/20',
          '103.21.244.0/22',
          '103.22.200.0/22',
          '103.31.4.0/22',
          '141.101.64.0/18',
          '108.162.192.0/18',
          '190.93.240.0/20',
          '188.114.96.0/20',
          '197.234.240.0/22',
          '198.41.128.0/17',
          '162.158.0.0/15',
          '104.16.0.0/13',
          '104.24.0.0/14',
          '172.64.0.0/13',
          '131.0.72.0/22',
        ]
  edge: # For portainer manager
    address: ':8000'
  dns: # For pihole
    address: ':53'
  dnsudp:
    address: ':53/udp'
  dnstls:
    address: ':853'

global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  filePath: /logs/traefik.log
  # format: 'common'
  level: DEBUG

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: proxy_traefik
    swarmMode: false
  file:
    directory: /dynamic-configs
    watch: true
